### ISSUE TITLE
Overlay layer not displaying after split

### ISSUE THREAD

**Issue by nouryf** [tobinbradley/timemachine#6]
Hi,

I cloned the repo and edited 3 files:
- "src/assets/overlays.js" to replace the overlays with one overlay layer
- "src/assets/surveys.json" to replace the layers with mine
- "src/store.js" to edit the maplocation with my map starting location and zoom level: export let mapLocation = writable([...

I start the dev server and I can see the map just fine
I went an enabled my overlay layer. I can see it just fine as well. 

I clicked the split control. The right map still shows the overlay but the left map does not show the overlays.
To refresh the left map, I disable the overlay layer and enabled it back on. This show the overlay layer.

Any way to fix this and have the overlay layer displayed automatically (if it was one) we the split operation occurs.
Or may be this is data dependent some how ?

If I don't do the mentioned edits and run the dev server, this "issue" does not occur.

Thanks

**Comment by nouryf** [comment]
I was able to duplicate this issue with the teamline as it is with only one change: I kept only one overlay layer (Roads).
So it seems like the issue is caused by the number of overlays layers in the 'overlays.js' file. Here is a screenshot of the timeline showing the issue duplicated:

![image](https://github.com/tobinbradley/timemachine/assets/18246160/7f49ed7c-38f2-4530-8501-81ddfea0bcb9)

Thanks

**Comment by nouryf** [comment]
After taking a closer look at this, it turns out that it's not related to the number of overlay layers. It's first overlay layer that does show this behavior. So this can be duplicated by the [current demo of the time machine](https://timemachine.mcmap.org/).

Start it, then enable the first overlayer layer ("2016 Tree Canopy") then click the "Split" control. The overlay layer is not displayed on the left side of the map:
![image](https://github.com/tobinbradley/timemachine/assets/18246160/a4db8617-ce83-4fb1-a790-3cb9592ccfa1)

Trying the other overlay layer work just fine. May be a 0 vs 1 indexed issue ?

**Comment by tobinbradley** [comment]
Thanks for all your detective work on this! I just pushed a fix.

Your assessment was dead on. By default the layer control automatically creates the z-index for each layer as it gets activated. When there's only one basemap, that z-index is 1 (basemap is 0). When the screen is split a second base map is added at z-index 1, which occupies the same z-index as the already on 1st layer in the layer control, so it sits on top of it. Toggle the layer off and on again, the layer control sees there are two layers and now assigns the first layer a z-index of 2. It didn't effect the other layer control layers because they're set 1 z-index higher than the first one which would clear two base layers. 

I fixed it by turning off auto z-index in the layer control and explicitly incrementally setting the z-index of the overlay layers starting with 2. 

Thanks again for reporting the problem! I likely never would have spotted it.
